<?php
/**
 * @author   Sven Friedemann <sven@erstellbar.de>
 * @license  Proprietary http://marwis.de/licence.txt
 * @link     http://marwis.de
 */
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Foundation\View\Helper\FlashMessenger' =>
        __DIR__ . '/src/Foundation/View/Helper/FlashMessenger.php',
    'Foundation\Form\View\Helper\FormElementErrors' =>
        __DIR__ . '/src/Foundation/Form/View/Helper/FormElementErrors.php',
    'Foundation\Form\View\Helper\FormElement' =>
        __DIR__ . '/src/Foundation/Form/View/Helper/FormElement.php',
    'Foundation\Module' => __DIR__ . '/Module.php',
);
